spring:
  application:
    name: batch-service
  config:
    import: 'optional:configserver:${config-server}'
    name: batch-service
  profiles:
    active: dev

#  kafka:
#    template:
#      default-topic: client_info
#    producer:
#      bootstrap-servers: 192.168.1.7:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
