server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dsa
    username: admin
    password: Sriban@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: false
  batch:
    jdbc:
      initialize-schema: EMBEDDED
    job:
      enabled: false



